[book]
authors = ["Janis Huser\n\ngit config --global user.name Janis"]
language = "en"
multilingual = false
src = "."
title = "ZHAW-BSC-Summary"


[output.katex]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor.katex]

[preprocessor.mermaid]
command = "mdbook-mermaid"
