[book]
title = "My ZHAW Notes"
authors = [ "Janis Huser" ]
language = "de"

[rust]
edition = "2018"

[output.html]
mathjax-support = true
site-url = "/ZHAW-BSC-Informatik"
git-repository-url = "https://github.com/JanisHuser/ZHAW-BSC-Informatik"
edit-url-template = "https://github.com/JanisHuser/ZHAW-BSC-Informatik/{path}"

[output.html.playground]
editable = true
line-numbers = true


[output.html.code.hidelines]
python = "~"


[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2