[book]
authors = ["Janis Huser"]
language = "de"
multilingual = true
src = ""
title = "BSC Computer Science Summary"


[output.html.playground]
editable = true

[output.html]
mathjax-support = true
additional-js = ["pyscript.js", "mermaid.min.js", "mermaid-init.js"]

[preprocessor.python]
command = "/home/mdbook/.cargo/bin/mdbook-python"

[preprocessor.mermaid]
