[book]
authors = ["Janis Huser"]
language = "de"
multilingual = true
src = ""
title = "BSC Computer Science Summary"


[output.html.playground]
editable = true

[output.html]
mathjax-support = true
additional-js = ["pyscript.js", "mermaid.min.js", "mermaid-init.js", "load-py-modules.js"]

#[preprocessor.python]
#command = "/home/mdbook/.cargo/bin/mdbook-python"

[preprocessor.mermaid]
command = "/home/mdbook/.cargo/bin/mdbook-mermaid"

[output.katex]

[preprocessor.katex]
command = "/home/mdbook/.cargo/bin/mdbook-katex"